title: Kamal Al Masoudi
description: Security labs & projects
minimal_mistakes_skin: dark
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# logo i topp (masthead)
logo: /assets/avatar.jpg

author:
  name: "Kamal Al Masoudi"
  avatar: /assets/avatar.jpg
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Masoudikamal"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kamal-al-masoudi/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kamal.a.masoudi@gmail.com"

navigation:
  enabled: true

